import { useEffect,useState } from 'react';
import { AlertTriangle,Bus,CheckCircle2,Send,Shield,ArrowLeft,MapPin,Clock } from 'lucide-react';
import { operationsIncidentService,incidentTypeLabel } from './services/IncidentService';
import type { IncidentStatus,IncidentType,OperationalIncident } from './types/incidents';
import { useTransportData } from './services/TransportContext';

const statusLabels:Record<IncidentStatus,string>={reported:'Reportada',under_review:'Em análise',in_progress:'Em curso',resolved:'Resolvida',closed:'Encerrada'};
const statusClass:Record<IncidentStatus,string>={reported:'status-reported',under_review:'status-review',in_progress:'status-active',resolved:'status-resolved',closed:'status-closed'};
const driverTypes:{id:IncidentType;label:string;icon:string}[]=[{id:'breakdown',label:'Avaria',icon:'🚌'},{id:'accident',label:'Acidente',icon:'🚧'},{id:'operational',label:'Outro incidente',icon:'⚠️'}];
const otherTypes:IncidentType[]=['heavy_traffic','road_restriction','significant_delay','cancelled_trip','route_change'];
function DemoHeader({title,description}:{title:string;description:string}){return <><a className="portal-back" href="/definicoes"><ArrowLeft size={15}/> Voltar à aplicação</a><div className="eyebrow">RT MOBILITY · AMBIENTE DE DEMONSTRAÇÃO</div><h1>{title}</h1><p>{description}</p><div className="portal-demo-warning"><Shield size={17}/> Simulação local. Não utilizar para comunicar ocorrências reais.</div></>}

export function DriverPortal(){const{routes,vehicles}=useTransportData();const[routeId,setRouteId]=useState(routes[0]?.id||'12'),[type,setType]=useState<IncidentType>('breakdown'),[other,setOther]=useState(false),[message,setMessage]=useState('');const route=routes.find(x=>x.id===routeId);const vehicle=vehicles.find(x=>x.routeId===routeId);
  const choose=(id:IncidentType)=>{setType(id);setOther(id==='operational');setMessage('');};
  return <section className="portal-page driver-portal"><DemoHeader title="Comunicar ocorrência" description="Regista rapidamente uma ocorrência para a equipa de operação."/><article className="driver-report-card"><h2>1. Escolhe a linha</h2><div className="portal-route-picks">{routes.map(item=><button key={item.id} className={routeId===item.id?'selected':''} onClick={()=>{setRouteId(item.id);setMessage('')}}><span style={{background:item.color}}><Bus size={16}/></span>{item.name}</button>)}</div><h2>2. O que aconteceu?</h2><div className="incident-type-picks">{driverTypes.map(item=><button key={item.id} className={type===item.id?'selected':''} onClick={()=>choose(item.id)}><span>{item.icon}</span><b>{item.label}</b></button>)}</div>{other&&<div className="other-type-picks" aria-label="Tipo de outro incidente">{otherTypes.map(item=><button key={item} className={type===item?'selected':''} onClick={()=>{setType(item);setMessage('')}}>{incidentTypeLabel[item]}</button>)}</div>}<div className="driver-private-note"><MapPin size={17}/><span>A posição do veículo, se disponível, é anexada apenas ao registo interno da operação. Não será mostrada aos passageiros.</span></div><button className="primary-btn driver-confirm" disabled={!route} onClick={()=>{if(!route)return;void operationsIncidentService.report({type,routeId,vehicleId:vehicle?.vehicleId,internalLocation:vehicle?[vehicle.latitude,vehicle.longitude]:undefined}).then(()=>setMessage(`Ocorrência de ${incidentTypeLabel[type].toLowerCase()} comunicada à central de demonstração.`))}}><Send size={17}/> Confirmar ocorrência</button>{message&&<div className="driver-success" role="status"><CheckCircle2 size={18}/>{message}</div>}</article><small className="portal-footnote">{route?.name||'Linha'} · veículo e localização apenas simulados · sem envio para uma entidade externa.</small></section>;
}

export function OperationsPortal(){const{routes}=useTransportData();const[items,setItems]=useState<OperationalIncident[]>([]);const[filter,setFilter]=useState<'active'|'all'>('active');const refresh=async()=>setItems(await operationsIncidentService.getIncidents());useEffect(()=>{void refresh();const changed=()=>void refresh();window.addEventListener('bus-track-incidents-changed',changed);return()=>window.removeEventListener('bus-track-incidents-changed',changed);},[]);const visible=items.filter(x=>filter==='all'||(x.status!=='closed'&&x.status!=='resolved'));
  const update=(id:string,patch:Parameters<typeof operationsIncidentService.update>[1])=>void operationsIncidentService.update(id,patch);
  return <section className="portal-page operations-portal"><DemoHeader title="Central operacional" description="Consulta e actualiza os registos internos do simulador."/><div className="ops-privacy"><Shield size={17}/><span>Esta vista é apenas uma simulação sem autenticação. Dados internos não são enviados nem disponibilizados na vista de passageiros.</span></div><div className="ops-toolbar"><div><b>Ocorrências</b><small>{items.filter(i=>i.status!=='closed'&&i.status!=='resolved').length} activas</small></div><div className="unit-choice"><button className={filter==='active'?'selected':''} onClick={()=>setFilter('active')}>Activas</button><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>Histórico</button></div></div>
    {visible.length===0?<div className="empty"><CheckCircle2 size={24}/><b>Sem ocorrências nesta vista</b></div>:<div className="ops-incident-list">{visible.map(item=><article className="ops-incident-card" key={item.id}><header><span className="ops-type-icon"><AlertTriangle size={18}/></span><div><b>{incidentTypeLabel[item.type]} · Linha {item.routeId}</b><small>Reportada {new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.reportedAt))}</small></div><span className={`incident-status ${statusClass[item.status]}`}>{statusLabels[item.status]}</span></header><div className="ops-internal-grid"><div><small>VEÍCULO (INTERNO)</small><b>{item.vehicleId||'Não indicado'}</b></div><div><small>POSIÇÃO SIMULADA (INTERNA)</small><b>{item.internalLocation?`${item.internalLocation[0].toFixed(5)}, ${item.internalLocation[1].toFixed(5)}`:'Não disponível'}</b></div><div><small>IMPACTO</small><b>{item.impactMinutes?`~${item.impactMinutes} min`:'Por avaliar'}</b></div></div><div className="ops-controls"><label>Linha<select value={item.routeId} onChange={e=>update(item.id,{routeId:e.target.value})}>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Estado<select value={item.status} onChange={e=>update(item.id,{status:e.target.value as IncidentStatus})}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Normalização prevista<input type="datetime-local" value={item.estimatedResolution?.slice(0,16)||''} onChange={e=>update(item.id,{estimatedResolution:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label><label>Impacto estimado (min)<input type="number" min="0" max="360" value={item.impactMinutes||0} onChange={e=>update(item.id,{impactMinutes:Number(e.target.value)})}/></label><label className="ops-note-field">Nota interna<textarea value={item.operatorNote||''} maxLength={240} onChange={e=>update(item.id,{operatorNote:e.target.value})} placeholder="Nota visível apenas nesta vista de demonstração"/></label></div><p className="ops-safe-preview"><b>Pré-visualização pública:</b> Perturbação na Linha {item.routeId}. A ocorrência poderá afectar o serviço. A localização não é partilhada.</p>{item.demo&&<small className="portal-footnote">Registo de demonstração; não recebido nem validado por uma operação real.</small>}</article>)}</div>}
  </section>;
}
