import { useEffect,useState } from 'react';
import { Bus,Clock,Printer,X,FileCheck2 } from 'lucide-react';
import { tripHistoryService,type TripHistoryItem,type TripProof } from './services/TripHistoryService';
import { useTransportData } from './services/TransportContext';

const formatDate=(value:string)=>new Intl.DateTimeFormat('pt-PT',{dateStyle:'long'}).format(new Date(`${value}T12:00:00`));
export default function TravelHistory(){const[trips,setTrips]=useState<TripHistoryItem[]>([]),[proof,setProof]=useState<TripProof|null>(null);const{routes,stops}=useTransportData();useEffect(()=>{void tripHistoryService.getHistory().then(setTrips);},[]);
  return <section className="travel-history"><div className="history-heading"><div><div className="section-kicker">REGISTOS NO DISPOSITIVO</div><h2>Histórico de viagens</h2><p>Consulta as viagens guardadas nesta demonstração.</p></div><span className="demo-history-badge">Demonstração</span></div>
    {trips.length===0?<div className="empty"><Bus size={24}/><b>Ainda não há viagens registadas</b><span>As viagens aparecerão aqui quando forem registadas pela plataforma.</span></div>:<div className="trip-list">{trips.map(trip=>{const route=routes.find(item=>item.id===trip.routeId),origin=stops.find(item=>item.id===trip.originStopId),destination=stops.find(item=>item.id===trip.destinationStopId);return <article className="trip-card" key={trip.id}><div className="trip-card-head"><div className="trip-line-icon" style={{background:route?.color||'#19a879'}}><Bus size={17}/></div><div><b>Viagem — {formatDate(trip.serviceDate)}</b><span>{route?.name||`Linha ${trip.routeId}`} · embarque aproximado às {trip.boardingTime}</span></div><span className="trip-demo-dot">Simulada</span></div><div className="trip-facts"><div><small>ORIGEM</small><b>{origin?.name||'Não disponível'}</b></div><div><small>DESTINO</small><b>{destination?.name||'Não indicado'}</b></div>{trip.vehicleId&&<div><small>VEÍCULO · SIMULADO</small><b>{trip.vehicleId}</b></div>}<div><small>PREVISTO</small><b>{trip.scheduledDeparture} · chegada {trip.scheduledArrival||'—'}</b></div><div><small>REGISTADO</small><b>{trip.actualArrival?`chegada aprox. ${trip.actualArrival}`:'Não disponível'}</b></div>{trip.estimatedDurationMinutes&&<div><small>DURAÇÃO ESTIMADA</small><b>{trip.estimatedDurationMinutes} min</b></div>}</div>{(trip.delayMinutes||0)>0&&<div className="trip-delay"><Clock size={16}/><strong>Atraso registado: +{trip.delayMinutes} min</strong></div>}{trip.incident&&<div className="trip-incident"><b>Ocorrência associada · {trip.incident.demo?'demonstração':'registo da plataforma'}</b><span>{trip.incident.status==='resolved'?'Serviço normalizado.':trip.incident.message}</span></div>}<button className="primary-btn proof-open" onClick={()=>void tripHistoryService.getProof(trip.id).then(setProof)}><FileCheck2 size={16}/> Gerar comprovativo</button></article>})}</div>}
    {proof&&<div className="proof-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setProof(null)}}><section className="proof-document" role="dialog" aria-modal="true" aria-labelledby="proof-title"><button className="proof-close no-print" aria-label="Fechar comprovativo" onClick={()=>setProof(null)}><X size={18}/></button><header className="proof-brand"><img src="/icon-192.png" alt=""/><div><b>Bus Track</b><small>Mobilidade urbana · Santarém</small></div></header><div className="proof-label">REGISTO AUTOMÁTICO DA PLATAFORMA</div><h2 id="proof-title">Comprovativo de viagem</h2><p className="proof-id">ID do registo: <b>{proof.proofId}</b></p><div className="proof-grid"><div><small>DATA</small><b>{formatDate(proof.trip.serviceDate)}</b></div><div><small>LINHA</small><b>{routes.find(r=>r.id===proof.trip.routeId)?.name||`Linha ${proof.trip.routeId}`}</b></div><div><small>ORIGEM</small><b>{stops.find(s=>s.id===proof.trip.originStopId)?.name||'Não disponível'}</b></div><div><small>DESTINO</small><b>{stops.find(s=>s.id===proof.trip.destinationStopId)?.name||'Não disponível'}</b></div>{proof.trip.vehicleId&&<div><small>VEÍCULO · SIMULADO</small><b>{proof.trip.vehicleId}</b></div>}<div><small>EMBARQUE APROXIMADO</small><b>{proof.trip.boardingTime}</b></div><div><small>CHEGADA PREVISTA</small><b>{proof.trip.scheduledArrival||'Não disponível'}</b></div><div><small>CHEGADA REGISTADA</small><b>{proof.trip.actualArrival||'Não disponível'}</b></div><div><small>DURAÇÃO ESTIMADA</small><b>{proof.trip.estimatedDurationMinutes?`${proof.trip.estimatedDurationMinutes} min`:'Não disponível'}</b></div></div>{(proof.trip.delayMinutes||0)>0&&<div className="proof-delay">Atraso registado: +{proof.trip.delayMinutes} minutos</div>}{proof.trip.incident&&<div className="proof-reason"><small>MOTIVO ASSOCIADO NO REGISTO</small><b>{proof.trip.incident.message}</b></div>}<div className="proof-issued">Emitido em {new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'short'}).format(new Date(proof.issuedAt))}</div><div className="proof-disclaimer">Documento gerado automaticamente a partir de dados registados pela plataforma. Este protótipo usa dados simulados; este comprovativo é apenas demonstrativo, não é uma declaração pessoal nem um documento oficial ou validado por um operador de transportes.</div><footer className="proof-actions no-print"><button className="secondary-btn" onClick={()=>setProof(null)}>Fechar</button><button className="primary-btn" onClick={()=>window.print()}><Printer size={16}/> Imprimir / Guardar em PDF</button></footer></section></div>}
  </section>;
}
